<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a</name>
   <tag></tag>
   <elementGuidId>f8de9d10-ce62-467a-8e9a-afa4ac1c3500</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.breadcrumb > li:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='checkout-checkout']/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Shopping Cart&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b0c3b0cb-fca3-4764-8b3a-0a8aaaa095d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://opencart.abstracta.us:80/index.php?route=checkout/cart</value>
      <webElementGuid>5ed0b54c-2682-4602-986e-49ae9c4d6ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shopping Cart</value>
      <webElementGuid>59c0ff95-08fd-4188-baf5-58700770aa18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkout-checkout&quot;)/ul[@class=&quot;breadcrumb&quot;]/li[2]/a[1]</value>
      <webElementGuid>48bb7519-c2d9-499a-a0b6-12a055a6fcd9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-checkout']/ul/li[2]/a</value>
      <webElementGuid>b19c15e7-9d59-4381-8f25-60f7d2f13fe4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Shopping Cart')]</value>
      <webElementGuid>e2bdf6f9-f207-4b08-b7c1-848a0655977a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show All MP3 Players'])[1]/following::a[2]</value>
      <webElementGuid>6dde9b45-c21b-4bab-8cab-d787baf91a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='test 9 (0)'])[1]/following::a[3]</value>
      <webElementGuid>7a02545f-a713-4dde-8314-123990e48721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[4]/preceding::a[1]</value>
      <webElementGuid>dd0389c7-19b4-4529-b090-62a976d68b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkout'])[5]/preceding::a[2]</value>
      <webElementGuid>b3a1e4f1-1df0-4e62-bfb5-8faa48ebc739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[@href='http://opencart.abstracta.us:80/index.php?route=checkout/cart'])[3]</value>
      <webElementGuid>5f7588e0-05a2-4d55-a1aa-e42e7fb1178a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a</value>
      <webElementGuid>e1684e26-332c-4b1f-967f-7f3ee05315eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://opencart.abstracta.us:80/index.php?route=checkout/cart' and (text() = 'Shopping Cart' or . = 'Shopping Cart')]</value>
      <webElementGuid>d812c956-3e88-4c39-9072-9123ac313853</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
